import { Course, StudyPlan, StudySession, User } from './types';

export const dummyUser: User = {
  id: '1',
  name: 'Maranatha Odai',
  email: 'maranathaokeleyodai@gmail.com',
  bio: 'Passionate student studying Computer Science with a focus on AI and machine learning.',
  university: 'University of Technology',
  major: 'Computer Science',
  year: '3rd Year',
  preferences: {
    darkMode: false,
    notifications: true,
    studyDays: [1,2,3,4,5],
    maxSlidesPerSession: 15,
    scheduleStartDate: new Date().toISOString(),
    scheduleEndDate: new Date(Date.now() + 21*86400000).toISOString(),
  },
};

export const dummyCourses: Course[] = [
  {
    id: '1',
    name: 'Advanced Mathematics',
    category: 'Mathematics',
    files: [
      {
        id: '1',
        name: 'Calculus_Chapter_1.pdf',
        type: 'pdf',
        size: 2048000,
        uploadedAt: new Date('2024-01-15'),
      },
      {
        id: '2',
        name: 'Linear_Algebra_Notes.pdf',
        type: 'pdf',
        size: 1536000,
        uploadedAt: new Date('2024-01-16'),
      },
    ],
    totalSlides: 120,
    completedSlides: 45,
    createdAt: new Date('2024-01-15'),
    color: '#007AFF',
    difficulty: 'hard',
    priority: 9,
  },
  {
    id: '2',
    name: 'Computer Science Fundamentals',
    category: 'Computer Science',
    files: [
      {
        id: '3',
        name: 'Data_Structures.pdf',
        type: 'pdf',
        size: 3072000,
        uploadedAt: new Date('2024-01-20'),
      },
    ],
    totalSlides: 80,
    completedSlides: 20,
    createdAt: new Date('2024-01-20'),
    color: '#34C759',
    difficulty: 'medium',
    priority: 6,
  },
  {
    id: '3',
    name: 'Physics Principles',
    category: 'Physics',
    files: [
      {
        id: '4',
        name: 'Quantum_Mechanics.pdf',
        type: 'pdf',
        size: 2560000,
        uploadedAt: new Date('2024-01-25'),
      },
    ],
    totalSlides: 95,
    completedSlides: 30,
    createdAt: new Date('2024-01-25'),
    color: '#FF9500',
    difficulty: 'hard',
    priority: 8,
  },
  {
    id: '4',
    name: 'Chemistry Lab',
    category: 'Chemistry',
    files: [
      {
        id: '5',
        name: 'Organic_Chemistry.pdf',
        type: 'pdf',
        size: 1800000,
        uploadedAt: new Date('2024-01-28'),
      },
    ],
    totalSlides: 60,
    completedSlides: 15,
    createdAt: new Date('2024-01-28'),
    color: '#FF3B30',
    difficulty: 'easy',
    priority: 4,
  },
];

export const dummySessions: StudySession[] = [
  {
    id: '1',
    courseId: '1',
    date: new Date(),
    slides: 12,
    completed: false,
    completedSlides: 0,
  },
  {
    id: '2',
    courseId: '2',
    date: new Date(Date.now() + 86400000),
    slides: 10,
    completed: false,
    completedSlides: 0,
  },
  {
    id: '3',
    courseId: '1',
    date: new Date(Date.now() + 2 * 86400000),
    slides: 8,
    completed: true,
    completedSlides: 8,
  },
  {
    id: '4',
    courseId: '3',
    date: new Date(Date.now() + 3 * 86400000),
    slides: 15,
    completed: false,
    completedSlides: 0,
  },
  {
    id: '5',
    courseId: '2',
    date: new Date(Date.now() + 3 * 86400000),
    slides: 12,
    completed: false,
    completedSlides: 0,
  },
  {
    id: '6',
    courseId: '4',
    date: new Date(Date.now() + 4 * 86400000),
    slides: 9,
    completed: false,
    completedSlides: 0,
  },
  {
    id: '7',
    courseId: '1',
    date: new Date(Date.now() + 5 * 86400000),
    slides: 10,
    completed: false,
    completedSlides: 0,
  },
  {
    id: '8',
    courseId: '3',
    date: new Date(Date.now() + 5 * 86400000),
    slides: 14,
    completed: false,
    completedSlides: 0,
  },
];

export const dummyStudyPlan: StudyPlan = {
  id: '1',
  courseId: '1',
  startDate: new Date(),
  endDate: new Date(Date.now() + 30 * 86400000),
  studyDays: [1, 2, 3, 4, 5],
  maxSlidesPerSession: 15,
  sessions: dummySessions,
};
