#!/bin/bash
# Database Setup Script for Smart Study Scheduler

echo "🗄️ Smart Study Scheduler Database Setup"
echo "========================================"
echo ""
echo "This script will help you set up the database schema in Supabase."
echo ""
echo "📋 Steps to complete:"
echo ""
echo "1. Go to your Supabase project dashboard"
echo "2. Navigate to the SQL Editor"
echo "3. Run the following SQL scripts in order:"
echo ""
echo "   a) First run: supabase-users-table.sql"
echo "   b) Then run: supabase-courses-schema.sql"
echo ""
echo "4. Verify the tables are created:"
echo "   - users"
echo "   - courses" 
echo "   - course_files"
echo "   - study_sessions"
echo ""
echo "5. Check that Row Level Security (RLS) is enabled"
echo ""
echo "📁 SQL files to run:"
echo "   - supabase-users-table.sql (creates users table)"
echo "   - supabase-courses-schema.sql (creates courses, course_files, study_sessions tables)"
echo ""
echo "⚠️  Important: Make sure to run these scripts in your Supabase SQL Editor!"
echo ""
echo "✅ After running the SQL scripts, your app will be able to:"
echo "   - Create and save courses"
echo "   - Upload and process files"
echo "   - Generate study schedules"
echo "   - Display data in calendar view"
echo ""
echo "🎉 Database setup complete!"
